import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.ERROR_MESSAGE;
import static javax.swing.JOptionPane.PLAIN_MESSAGE;
import static javax.swing.JOptionPane.QUESTION_MESSAGE;


public class LoginPage extends javax.swing.JFrame {
    public static String nm;
    public static String Admn;
    public static Connection c = null;
    public static Statement s = null;
    public static ResultSet rs = null;
    public void connect()
    {
        try
        {
            Class.forName("java.sql.DriverManager");
            c = DriverManager.getConnection("jdbc:mysql://localhost:3306/IP_Project","root","admin");
            s = c.createStatement();
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }

    /**
     * Creates new form LoginPage
     */
    public LoginPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        user_tf = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        pass_tf = new javax.swing.JPasswordField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login Page");
        setBackground(new java.awt.Color(0, 126, 146));
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Login", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 15))); // NOI18N
        jPanel1.setOpaque(false);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 0));
        jLabel1.setText("Username:");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 0, 0));
        jLabel2.setText("Password:");

        user_tf.setToolTipText("Enter UserName");

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(153, 0, 0));
        jButton1.setText("Login");
        jButton1.setToolTipText("Click to Login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        pass_tf.setToolTipText("Enter Password");
        pass_tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pass_tfActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(153, 0, 0));
        jButton2.setText("Forgot Password?");
        jButton2.setToolTipText("Click to reset Password");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                        .addComponent(jButton2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(44, 44, 44)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(user_tf)
                            .addComponent(pass_tf))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(user_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel2))
                    .addComponent(pass_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(64, 64, 64))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(320, 130, 330, 230);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rsz_backbutton.jpg"))); // NOI18N
        jButton3.setToolTipText("Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(900, 20, 50, 50);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rsz_city_scape5b.jpg"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 1000, 510);

        setSize(new java.awt.Dimension(1016, 545));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
String Username = user_tf.getText();
String P = new String(pass_tf.getPassword());
if (Username.isEmpty() || P.isEmpty())
{
    JOptionPane.showMessageDialog(null, "Please Enter UserName and Password", "Empty Field", ERROR_MESSAGE);
}
else {
String q;
try
{
    connect();
    if (StartPage.i==2)
    {
        q = "Select Name, UserName, Password from Students, id_students where Students.AdmNo = id_students.USername && UserName = '"+Username+"';";
        rs = s.executeQuery(q);
        if(rs.next())
        {
            String p = rs.getString("Password");
            nm = rs.getString("Name");
            if (p.equals(P))
            {
                JOptionPane.showMessageDialog(rootPane, "Welcome "+nm, "Welcome", PLAIN_MESSAGE);
                Admn = rs.getString("UserName");
                new StudentPage().setVisible(true);
                this.dispose();
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Incorrect Password", "Incorrect Password", ERROR_MESSAGE);
                user_tf.setText("");
                pass_tf.setText("");
            }
        }
        else
        {
            JOptionPane.showMessageDialog(null, "No such User Exsist!", "Invalid UserName", ERROR_MESSAGE);
            user_tf.setText("");
            pass_tf.setText("");
        }
    }
    else if (StartPage.i==1)
    {
        q = "Select Name, Password, Department from employees, id_employees where Employees.EmpCode = id_employees.Username && Username = '"+Username+"';";
        rs = s.executeQuery(q);
        if(rs.next())
        {
            String p = rs.getString("Password");
            String d = rs.getString("Department");
            nm = rs.getString("Name");
            if (p.equals(P))
            {
                JOptionPane.showMessageDialog(rootPane, "Welcome "+nm, "Welcome", PLAIN_MESSAGE);
                if (d.equals("Fees"))
                {
                    new Fees().setVisible(true);
                    this.dispose();   
                }
                else if (d.equals("Material"))
                {
                    new Material().setVisible(true);
                    this.dispose();   
                }
                else if (d.equals("Admission"))
                {
                    new NewAdmission().setVisible(true);
                    this.dispose();   
                }
                else if (d.equals("Manager"))
                {
                    new Manager().setVisible(true);
                    this.dispose();
                }
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Incorrect Password", "Incorrect Password", ERROR_MESSAGE);
                user_tf.setText("");
                pass_tf.setText("");
            }
        }
        else
        {
            JOptionPane.showMessageDialog(null, "No such User Exsist!", "Invalid UserName", ERROR_MESSAGE);
            user_tf.setText("");
            pass_tf.setText("");
        }
    }
}
catch(Exception e)
{
    JOptionPane.showMessageDialog(null, e.getMessage(), "Error", ERROR_MESSAGE);
}}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
String UserName = JOptionPane.showInputDialog(rootPane, "Enter your UserName", "Enter UserName", QUESTION_MESSAGE);
String security_question="";
String security_answer="";
String sa="";
String password;
try
{
    connect();
    if (StartPage.i==2)
        {
            String q = "Select security_question, security_answer from id_students where UserName = '"+UserName+"';";
            rs = s.executeQuery(q);
        }
    else if (StartPage.i==1)
    {
            String q = "Select security_question, security_answer from id_employees where UserName = '"+UserName+"';";
            rs = s.executeQuery(q);
    }
    if (rs.next())
    {
        security_question = rs.getString("security_question");
        security_answer = rs.getString("security_answer");
        sa = JOptionPane.showInputDialog(rootPane, security_question, "Answer Security Question", QUESTION_MESSAGE);
        if (security_answer.equals(sa))
        {
            password = JOptionPane.showInputDialog(null, "Enter New Password");
            if (StartPage.i==2)
            {
                String q1 = "Update id_students set password = '"+password+"' where Username = '"+UserName+"';";
                s.executeUpdate(q1);
            }
            else if (StartPage.i==1)
            {
                String q1 = "Update id_employees set password = '"+password+"' where Username = '"+UserName+"';";
                s.executeUpdate(q1);
            }
            
            JOptionPane.showMessageDialog(null, "Password changed");
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Incorrect Answer", "Incorrect Answer", ERROR_MESSAGE);
        }
    }
    else
    {
        JOptionPane.showMessageDialog(null, "No such UserName", "Invalid UserName", ERROR_MESSAGE);
    }
}
catch (Exception e)
{
    JOptionPane.showMessageDialog(null, e.getMessage(), "Error", ERROR_MESSAGE);
}
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
new StartPage().setVisible(true);
this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void pass_tfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pass_tfActionPerformed
String Username = user_tf.getText();
String P = new String(pass_tf.getPassword());
if (Username.isEmpty() || P.isEmpty())
{
    JOptionPane.showMessageDialog(null, "Please Enter UserName and Password", "Empty Field", ERROR_MESSAGE);
}
else {
String q;
try
{
    connect();
    if (StartPage.i==2)
    {
        q = "Select Name, UserName, Password from Students, id_students where Students.AdmNo = id_students.USername && UserName = '"+Username+"';";
        rs = s.executeQuery(q);
        if(rs.next())
        {
            String p = rs.getString("Password");
            nm = rs.getString("Name");
            if (p.equals(P))
            {
                JOptionPane.showMessageDialog(rootPane, "Welcome "+nm, "Welcome", PLAIN_MESSAGE);
                Admn = rs.getString("UserName");
                new StudentPage().setVisible(true);
                this.dispose();
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Incorrect Password", "Incorrect Password", ERROR_MESSAGE);
                user_tf.setText("");
                pass_tf.setText("");
            }
        }
        else
        {
            JOptionPane.showMessageDialog(null, "No such User Exsist!", "Invalid UserName", ERROR_MESSAGE);
            user_tf.setText("");
            pass_tf.setText("");
        }
    }
    else if (StartPage.i==1)
    {
        q = "Select Name, Password, Department from employees, id_employees where Employees.EmpCode = id_employees.Username && Username = '"+Username+"';";
        rs = s.executeQuery(q);
        if(rs.next())
        {
            String p = rs.getString("Password");
            String d = rs.getString("Department");
            nm = rs.getString("Name");
            if (p.equals(P))
            {
                JOptionPane.showMessageDialog(rootPane, "Welcome "+nm, "Welcome", PLAIN_MESSAGE);
                if (d.equals("Fees"))
                {
                    new Fees().setVisible(true);
                    this.dispose();   
                }
                else if (d.equals("Material"))
                {
                    new Material().setVisible(true);
                    this.dispose();   
                }
                else if (d.equals("Admission"))
                {
                    new NewAdmission().setVisible(true);
                    this.dispose();   
                }
                else if (d.equals("Manager"))
                {
                    new Manager().setVisible(true);
                    this.dispose();
                }
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Incorrect Password", "Incorrect Password", ERROR_MESSAGE);
                user_tf.setText("");
                pass_tf.setText("");
            }
        }
        else
        {
            JOptionPane.showMessageDialog(null, "No such User Exsist!", "Invalid UserName", ERROR_MESSAGE);
            user_tf.setText("");
            pass_tf.setText("");
        }
    }
}
catch(Exception e)
{
    JOptionPane.showMessageDialog(null, e.getMessage(), "Error", ERROR_MESSAGE);
}}
    }//GEN-LAST:event_pass_tfActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField pass_tf;
    private javax.swing.JTextField user_tf;
    // End of variables declaration//GEN-END:variables
}
