import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

public class StartPage extends javax.swing.JFrame {
    public static int i=1;
    public static Connection c = null;
    public static Statement s = null;
    public static ResultSet rs = null;
    public void connect()
    {
        try
        {
            Class.forName("java.sql.DriverManager");
            c = DriverManager.getConnection("jdbc:mysql://localhost:3306/IP_Project","root","admin");
            s = c.createStatement();
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }

            
    /**
     * Creates new form StartPage
     */
    public StartPage() {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Admin_button = new javax.swing.JButton();
        stud_button = new javax.swing.JButton();
        Exit1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Welcome");
        setIconImages(null);
        getContentPane().setLayout(null);

        Admin_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rsz_1download.jpg"))); // NOI18N
        Admin_button.setToolTipText("Administrator Login");
        Admin_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Admin_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(Admin_button);
        Admin_button.setBounds(580, 220, 110, 110);

        stud_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rsz_download.jpg"))); // NOI18N
        stud_button.setToolTipText("Student Login");
        stud_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stud_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(stud_button);
        stud_button.setBounds(250, 220, 110, 110);

        Exit1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rsz_1exit.jpg"))); // NOI18N
        Exit1.setToolTipText("Exit");
        Exit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Exit1ActionPerformed(evt);
            }
        });
        getContentPane().add(Exit1);
        Exit1.setBounds(930, 20, 50, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rsz_team-building-coaching-exercise.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1000, 520);

        setSize(new java.awt.Dimension(1015, 557));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Admin_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Admin_buttonActionPerformed
new LoginPage().setVisible(true);
this.dispose();
StartPage.i = 1;
    }//GEN-LAST:event_Admin_buttonActionPerformed

    private void stud_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stud_buttonActionPerformed
new LoginPage().setVisible(true);
this.dispose();
StartPage.i = 2;
    }//GEN-LAST:event_stud_buttonActionPerformed

    private void Exit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Exit1ActionPerformed
System.exit(0);
    }//GEN-LAST:event_Exit1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        int i = 1; /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StartPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StartPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StartPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StartPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StartPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Admin_button;
    private javax.swing.JButton Exit1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton stud_button;
    // End of variables declaration//GEN-END:variables
}
